pycodestyle:
    max-line-length: 200  # Default is 79 in PEP8
    ignore:  # Errors and warnings to ignore
        - E122 # Continuation line missing indentation or outdented
        - E126 # Continuation line over-indented for hanging indent
        - E127 # Continuation line over-indented for visual indent
        - E741 # Do not use variables named I, O or l
        - W504 # Line break before / after binary operator
